version: '3.8'

services:
  nextjs:
    container_name: deep_link_web
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3200:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    command: npm run dev
    restart: unless-stopped

